application: haritzmedina-kaixomundua
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheet
  static_dir: css

- url: /images
  static_dir: img

- url: /.*
  script: kaixomundua.app

libraries:
- name: webapp2
  version: "2.5.2"
